schema: SimV1
name: toscaCloudInventory

connections:
  - name: inventoryApi
    port: 21004
    listen: true

services:
  - name: playlistsService
    description: Simulates the Tosca Cloud Playlists Inventory API
    steps:
      - direction: In
        name: receiveArtifactsRequest
        from: inventoryApi
        trigger:
          - type: Path
            value: "/api/v3/artifacts/search"
      - direction: Out
        name: sendArtifactsResponse
        to: inventoryApi
        message:
          payload: |-
            {"total":0,"items":[],"previousPageToken":null,"currentPageToken":"AAAABYim0poAAz/m\u002BL37AwQAAAAAAAiLHwAAAAU=","nextPageToken":null}
