schema: SimV1
name: toscaCloudInventoryTest

connections:
  - name: inventoryApi
    endpoint: http://localhost:21004
    listen: false

services:
  - name: testInventoryService
    description: Tests the Tosca Cloud Inventory API
    steps:
      - direction: Out
        name: sendArtifactsRequest
        to: inventoryApi
        insert:
          - type: Path
            value: /api/v3/artifacts/search
          - type: QueryParam
            key: tenantId
            value: fusionx
          - type: QueryParam
            key: spaceId
            value: default
          - type: Method
            value: GET

      - direction: In
        name: verifyArtifactsResponse
        from: inventoryApi
        verify:
          - jsonPath: $.total
            value: 0
          - jsonPath: $.items
            exists: true
          - jsonPath: $.previousPageToken
            value: null
